### PR TITLE
Create issue templates, Contributing guidelines

### PR DESCRIPTION
**Pull request by garrettsummerfi3ld**
Add issue templates for this repository for bug reporting and feature requests.

Add new contributing guidelines for outside contributors to add new features or report bugs.

### CODE REVIEW

**Review by ciph0n — APPROVED** [review]
Approved.

**Review by ciph0n — APPROVED** [review]
Approved.

**Comment by ciph0n** [comment]
@yosef022 approv

**Review by yosef022 — APPROVED** [review]
looks good bud

**Pull request merged**
